[
  # False positive generated as module is dynamically generated by Igniter
  {"lib/mix/tasks/jido_vfs.install.ex",:unknown_function},
  {"lib/mix/tasks/jido_vfs.install.ex",:callback_info_missing}
]
